/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package Data-Structures.linkedList;

public class App {


    public static void main(String[] args) {

       linkedList mylist = new linkedList();
        mylist.insert(5);
        mylist.insert(8);
        mylist.insert(15);

        System.out.println(mylist.includes(15));
        System.out.println(mylist.includes(20));


        System.out.println(mylist.toString());


    }
}
