/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utilities;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args)
    {
       AnimalShelter a =  new AnimalShelter();

       Animal animal = new Cat("cat1");
       Animal animal2 = new Dog("dog1");
        Animal animal3 = new Dog("dog2");

       a.enqueue(animal);
       a.enqueue(animal2);
        a.enqueue(animal3);

       System.out.println(a.dequeue("cat"));
        System.out.println(a.dequeue("dog"));
        System.out.println(a.queue1.peek()[0]);
    }
}
