/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package Data-Structures.linkedList;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testToString() {

        linkedList test = new linkedList();

        String expected = "linkedList is empty...";


        assertEquals("the linkedList should be empty...", expected, test.toString());

    }

    @Test public void testInsert(){
        linkedList test = new linkedList();
        test.insert(5);

        String expected = "{5}->null";

        assertEquals("an error occurred inserting in linkedList...", expected, test.toString());

    }

    @Test public void testincludes(){

        linkedList test = new linkedList();
        test.insert(5);

        assertTrue("an error occurred testing the include function...", test.includes(5));



    }



}
