/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stacksandqueues;

public class App {


    public static void main(String[] args) {

        Stack stack1 = new Stack();
//        stack1.push(2);
//        stack1.push(5);
//        stack1.push(6);

//        stack1.pop();
//
//        System.out.println(stack1.peek());
//
//        System.out.println(stack1.isEmpty());
//
//        System.out.println(stack1.toString());

        Queue queue1 = new Queue();
//
        queue1.enqueue(1);
        queue1.enqueue(2);
        queue1.enqueue(3);
//        System.out.println(queue1.toString());

//
//        queue1.dequeue();
//        queue1.dequeue();
//
//        System.out.println(queue1.dequeue());



//        System.out.println(queue1.peek());
//        System.out.println(queue1.isEmpty());


        // code-challenge-11

        PseudoQueue pseudoQueue1 = new PseudoQueue();
        pseudoQueue1.enqueue(20);
        pseudoQueue1.enqueue(15);
        pseudoQueue1.enqueue(10);
        pseudoQueue1.enqueue(5);

        System.out.println(pseudoQueue1.s1.peek());
        System.out.println(pseudoQueue1.dequeue());




    }
}
