/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        BinaryTree  myTree = new BinaryTree ();



        myTree.add(7);
        myTree.add(8);
        myTree.add(6);
        myTree.add(10);
        myTree.add(9);
//
//
        System.out.println(myTree.PreOrder());
        System.out.println(myTree.inOrder());
        System.out.println(myTree.PostOrder());

        System.out.println(myTree.contains(8));
        System.out.println(myTree.contains(10));
        System.out.println(myTree.contains(1));

    }
}
